// Copyright 2024 JC-Lab
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.15.8
// source: kms.proto

package kms

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TpmWrappedData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pcrs        []int32 `protobuf:"varint,9,rep,packed,name=pcrs,proto3" json:"pcrs,omitempty"`
	PrivateArea []byte  `protobuf:"bytes,10,opt,name=private_area,json=privateArea,proto3" json:"private_area,omitempty"`
	PublicArea  []byte  `protobuf:"bytes,11,opt,name=public_area,json=publicArea,proto3" json:"public_area,omitempty"`
}

func (x *TpmWrappedData) Reset() {
	*x = TpmWrappedData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kms_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TpmWrappedData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TpmWrappedData) ProtoMessage() {}

func (x *TpmWrappedData) ProtoReflect() protoreflect.Message {
	mi := &file_kms_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TpmWrappedData.ProtoReflect.Descriptor instead.
func (*TpmWrappedData) Descriptor() ([]byte, []int) {
	return file_kms_proto_rawDescGZIP(), []int{0}
}

func (x *TpmWrappedData) GetPcrs() []int32 {
	if x != nil {
		return x.Pcrs
	}
	return nil
}

func (x *TpmWrappedData) GetPrivateArea() []byte {
	if x != nil {
		return x.PrivateArea
	}
	return nil
}

func (x *TpmWrappedData) GetPublicArea() []byte {
	if x != nil {
		return x.PublicArea
	}
	return nil
}

type KmsWrappedData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version      int32  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	KeyId        []byte `protobuf:"bytes,9,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	EncryptedDek []byte `protobuf:"bytes,10,opt,name=encrypted_dek,json=encryptedDek,proto3" json:"encrypted_dek,omitempty"`
	Nonce        []byte `protobuf:"bytes,11,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Ciphertext   []byte `protobuf:"bytes,12,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"`
}

func (x *KmsWrappedData) Reset() {
	*x = KmsWrappedData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kms_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KmsWrappedData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KmsWrappedData) ProtoMessage() {}

func (x *KmsWrappedData) ProtoReflect() protoreflect.Message {
	mi := &file_kms_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KmsWrappedData.ProtoReflect.Descriptor instead.
func (*KmsWrappedData) Descriptor() ([]byte, []int) {
	return file_kms_proto_rawDescGZIP(), []int{1}
}

func (x *KmsWrappedData) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *KmsWrappedData) GetKeyId() []byte {
	if x != nil {
		return x.KeyId
	}
	return nil
}

func (x *KmsWrappedData) GetEncryptedDek() []byte {
	if x != nil {
		return x.EncryptedDek
	}
	return nil
}

func (x *KmsWrappedData) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *KmsWrappedData) GetCiphertext() []byte {
	if x != nil {
		return x.Ciphertext
	}
	return nil
}

type ExportFile struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version int32 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	// salt
	// since version 1
	Salt []byte `protobuf:"bytes,11,opt,name=salt,proto3" json:"salt,omitempty"`
	// iteration count
	// since version 1
	Iteration int32 `protobuf:"varint,12,opt,name=iteration,proto3" json:"iteration,omitempty"`
	// since version 1
	Iv         []byte `protobuf:"bytes,21,opt,name=iv,proto3" json:"iv,omitempty"`
	Ciphertext []byte `protobuf:"bytes,22,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"`
}

func (x *ExportFile) Reset() {
	*x = ExportFile{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kms_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExportFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportFile) ProtoMessage() {}

func (x *ExportFile) ProtoReflect() protoreflect.Message {
	mi := &file_kms_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportFile.ProtoReflect.Descriptor instead.
func (*ExportFile) Descriptor() ([]byte, []int) {
	return file_kms_proto_rawDescGZIP(), []int{2}
}

func (x *ExportFile) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ExportFile) GetSalt() []byte {
	if x != nil {
		return x.Salt
	}
	return nil
}

func (x *ExportFile) GetIteration() int32 {
	if x != nil {
		return x.Iteration
	}
	return 0
}

func (x *ExportFile) GetIv() []byte {
	if x != nil {
		return x.Iv
	}
	return nil
}

func (x *ExportFile) GetCiphertext() []byte {
	if x != nil {
		return x.Ciphertext
	}
	return nil
}

var File_kms_proto protoreflect.FileDescriptor

var file_kms_proto_rawDesc = []byte{
	0x0a, 0x09, 0x6b, 0x6d, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x19, 0x6a, 0x63, 0x6c,
	0x61, 0x62, 0x2e, 0x6b, 0x38, 0x73, 0x74, 0x70, 0x6d, 0x6b, 0x6d, 0x73, 0x70, 0x6c, 0x75, 0x67,
	0x69, 0x6e, 0x2e, 0x6b, 0x6d, 0x73, 0x22, 0x68, 0x0a, 0x0e, 0x54, 0x70, 0x6d, 0x57, 0x72, 0x61,
	0x70, 0x70, 0x65, 0x64, 0x44, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x63, 0x72, 0x73,
	0x18, 0x09, 0x20, 0x03, 0x28, 0x05, 0x52, 0x04, 0x70, 0x63, 0x72, 0x73, 0x12, 0x21, 0x0a, 0x0c,
	0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x5f, 0x61, 0x72, 0x65, 0x61, 0x18, 0x0a, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x0b, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x41, 0x72, 0x65, 0x61, 0x12,
	0x1f, 0x0a, 0x0b, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x61, 0x72, 0x65, 0x61, 0x18, 0x0b,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x41, 0x72, 0x65, 0x61,
	0x22, 0x9c, 0x01, 0x0a, 0x0e, 0x4b, 0x6d, 0x73, 0x57, 0x72, 0x61, 0x70, 0x70, 0x65, 0x64, 0x44,
	0x61, 0x74, 0x61, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x15, 0x0a,
	0x06, 0x6b, 0x65, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x6b,
	0x65, 0x79, 0x49, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x65, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x65,
	0x64, 0x5f, 0x64, 0x65, 0x6b, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0c, 0x65, 0x6e, 0x63,
	0x72, 0x79, 0x70, 0x74, 0x65, 0x64, 0x44, 0x65, 0x6b, 0x12, 0x14, 0x0a, 0x05, 0x6e, 0x6f, 0x6e,
	0x63, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x12,
	0x1e, 0x0a, 0x0a, 0x63, 0x69, 0x70, 0x68, 0x65, 0x72, 0x74, 0x65, 0x78, 0x74, 0x18, 0x0c, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x0a, 0x63, 0x69, 0x70, 0x68, 0x65, 0x72, 0x74, 0x65, 0x78, 0x74, 0x22,
	0x88, 0x01, 0x0a, 0x0a, 0x45, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x61, 0x6c, 0x74,
	0x18, 0x0b, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x73, 0x61, 0x6c, 0x74, 0x12, 0x1c, 0x0a, 0x09,
	0x69, 0x74, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x09, 0x69, 0x74, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x76,
	0x18, 0x15, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x02, 0x69, 0x76, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x69,
	0x70, 0x68, 0x65, 0x72, 0x74, 0x65, 0x78, 0x74, 0x18, 0x16, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a,
	0x63, 0x69, 0x70, 0x68, 0x65, 0x72, 0x74, 0x65, 0x78, 0x74, 0x42, 0x2a, 0x5a, 0x28, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6a, 0x63, 0x2d, 0x6c, 0x61, 0x62, 0x2f,
	0x6b, 0x38, 0x73, 0x2d, 0x74, 0x70, 0x6d, 0x2d, 0x6b, 0x6d, 0x73, 0x2d, 0x70, 0x6c, 0x75, 0x67,
	0x69, 0x6e, 0x2f, 0x6b, 0x6d, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_kms_proto_rawDescOnce sync.Once
	file_kms_proto_rawDescData = file_kms_proto_rawDesc
)

func file_kms_proto_rawDescGZIP() []byte {
	file_kms_proto_rawDescOnce.Do(func() {
		file_kms_proto_rawDescData = protoimpl.X.CompressGZIP(file_kms_proto_rawDescData)
	})
	return file_kms_proto_rawDescData
}

var file_kms_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_kms_proto_goTypes = []interface{}{
	(*TpmWrappedData)(nil), // 0: jclab.k8stpmkmsplugin.kms.TpmWrappedData
	(*KmsWrappedData)(nil), // 1: jclab.k8stpmkmsplugin.kms.KmsWrappedData
	(*ExportFile)(nil),     // 2: jclab.k8stpmkmsplugin.kms.ExportFile
}
var file_kms_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_kms_proto_init() }
func file_kms_proto_init() {
	if File_kms_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_kms_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TpmWrappedData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kms_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KmsWrappedData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kms_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExportFile); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_kms_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kms_proto_goTypes,
		DependencyIndexes: file_kms_proto_depIdxs,
		MessageInfos:      file_kms_proto_msgTypes,
	}.Build()
	File_kms_proto = out.File
	file_kms_proto_rawDesc = nil
	file_kms_proto_goTypes = nil
	file_kms_proto_depIdxs = nil
}
